/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated TypeScript interfaces from Swagger specification
 * Do not edit this file manually
 */
import { HttpContext, HttpHeaders } from '@angular/common/http';
export interface RegisterDto {
  /** Email address of the user */
  email: string;
  /** Password for the user account */
  password: string;
}

export interface User {
  /** Unique identifier of the user */
  id: number;
  /** Unique email for the user */
  email: string;
  /** User password (hashed) */
  password: string;
  /** Role of the user */
  role: 'user' | 'admin';
  /** Timestamp when the user was created */
  createdAt: Date;
}

export interface LoginDto {
  /** Email address of the user */
  email: string;
  /** Password for the user account */
  password: string;
  /** Whether to keep the user signed in */
  staySignedIn?: boolean;
}

export interface ChangePasswordDto {
  /** New password for the user account */
  password: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
  headers?: HttpHeaders;
  reportProgress?: boolean;
  responseType?: TResponseType;
  withCredentials?: boolean;
  context?: HttpContext;
}
