/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Authentication controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ChangePasswordDto, LoginDto, RegisterDto, RequestOptions, User } from '../models';
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from '../tokens';

@Injectable({ providedIn: 'root' })
export class AuthenticationService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  getCsrf(observe?: 'body', options?: RequestOptions<'json'>): Observable<Record<string, any>>;
  getCsrf(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<Record<string, any>>>;
  getCsrf(
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<Record<string, any>>>;
  getCsrf(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/csrf`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  register(
    registerDto: RegisterDto,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<User>;
  register(
    registerDto: RegisterDto,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<User>>;
  register(
    registerDto: RegisterDto,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<User>>;
  register(
    registerDto: RegisterDto,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/register`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.post(url, registerDto, requestOptions);
  }

  login(loginDto: LoginDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
  login(
    loginDto: LoginDto,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  login(
    loginDto: LoginDto,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  login(
    loginDto: LoginDto,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/login`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.post(url, loginDto, requestOptions);
  }

  logout(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
  logout(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
  logout(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
  logout(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/logout`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.post(url, null, requestOptions);
  }

  getCurrentUser(observe?: 'body', options?: RequestOptions<'json'>): Observable<User>;
  getCurrentUser(
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<User>>;
  getCurrentUser(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<User>>;
  getCurrentUser(
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/user`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  changeUserPassword(
    changePasswordDto: ChangePasswordDto,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  changeUserPassword(
    changePasswordDto: ChangePasswordDto,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  changeUserPassword(
    changePasswordDto: ChangePasswordDto,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  changeUserPassword(
    changePasswordDto: ChangePasswordDto,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/auth/change-password`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.put(url, changePasswordDto, requestOptions);
  }
}
